// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wantslist.proto

package wantslist

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type WantListEntry_Status int32

const (
	WantListEntry_UNPROCESSED WantListEntry_Status = 0
	WantListEntry_WANTED      WantListEntry_Status = 1
	WantListEntry_COMPLETE    WantListEntry_Status = 3
)

var WantListEntry_Status_name = map[int32]string{
	0: "UNPROCESSED",
	1: "WANTED",
	3: "COMPLETE",
}

var WantListEntry_Status_value = map[string]int32{
	"UNPROCESSED": 0,
	"WANTED":      1,
	"COMPLETE":    3,
}

func (x WantListEntry_Status) String() string {
	return proto.EnumName(WantListEntry_Status_name, int32(x))
}

func (WantListEntry_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c74c703880358ab0, []int{1, 0}
}

type Config struct {
	Lists                []*WantList `protobuf:"bytes,1,rep,name=lists,proto3" json:"lists,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_c74c703880358ab0, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetLists() []*WantList {
	if m != nil {
		return m.Lists
	}
	return nil
}

type WantListEntry struct {
	Want                 int32                `protobuf:"varint,1,opt,name=want,proto3" json:"want,omitempty"`
	Index                int32                `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Status               WantListEntry_Status `protobuf:"varint,3,opt,name=status,proto3,enum=wantslist.WantListEntry_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *WantListEntry) Reset()         { *m = WantListEntry{} }
func (m *WantListEntry) String() string { return proto.CompactTextString(m) }
func (*WantListEntry) ProtoMessage()    {}
func (*WantListEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_c74c703880358ab0, []int{1}
}

func (m *WantListEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WantListEntry.Unmarshal(m, b)
}
func (m *WantListEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WantListEntry.Marshal(b, m, deterministic)
}
func (m *WantListEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WantListEntry.Merge(m, src)
}
func (m *WantListEntry) XXX_Size() int {
	return xxx_messageInfo_WantListEntry.Size(m)
}
func (m *WantListEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_WantListEntry.DiscardUnknown(m)
}

var xxx_messageInfo_WantListEntry proto.InternalMessageInfo

func (m *WantListEntry) GetWant() int32 {
	if m != nil {
		return m.Want
	}
	return 0
}

func (m *WantListEntry) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *WantListEntry) GetStatus() WantListEntry_Status {
	if m != nil {
		return m.Status
	}
	return WantListEntry_UNPROCESSED
}

type WantList struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Wants                []*WantListEntry `protobuf:"bytes,2,rep,name=wants,proto3" json:"wants,omitempty"`
	LastProcessTime      int64            `protobuf:"varint,3,opt,name=last_process_time,json=lastProcessTime,proto3" json:"last_process_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *WantList) Reset()         { *m = WantList{} }
func (m *WantList) String() string { return proto.CompactTextString(m) }
func (*WantList) ProtoMessage()    {}
func (*WantList) Descriptor() ([]byte, []int) {
	return fileDescriptor_c74c703880358ab0, []int{2}
}

func (m *WantList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WantList.Unmarshal(m, b)
}
func (m *WantList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WantList.Marshal(b, m, deterministic)
}
func (m *WantList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WantList.Merge(m, src)
}
func (m *WantList) XXX_Size() int {
	return xxx_messageInfo_WantList.Size(m)
}
func (m *WantList) XXX_DiscardUnknown() {
	xxx_messageInfo_WantList.DiscardUnknown(m)
}

var xxx_messageInfo_WantList proto.InternalMessageInfo

func (m *WantList) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WantList) GetWants() []*WantListEntry {
	if m != nil {
		return m.Wants
	}
	return nil
}

func (m *WantList) GetLastProcessTime() int64 {
	if m != nil {
		return m.LastProcessTime
	}
	return 0
}

type AddWantListRequest struct {
	Add                  *WantList `protobuf:"bytes,1,opt,name=add,proto3" json:"add,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddWantListRequest) Reset()         { *m = AddWantListRequest{} }
func (m *AddWantListRequest) String() string { return proto.CompactTextString(m) }
func (*AddWantListRequest) ProtoMessage()    {}
func (*AddWantListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c74c703880358ab0, []int{3}
}

func (m *AddWantListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddWantListRequest.Unmarshal(m, b)
}
func (m *AddWantListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddWantListRequest.Marshal(b, m, deterministic)
}
func (m *AddWantListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddWantListRequest.Merge(m, src)
}
func (m *AddWantListRequest) XXX_Size() int {
	return xxx_messageInfo_AddWantListRequest.Size(m)
}
func (m *AddWantListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddWantListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddWantListRequest proto.InternalMessageInfo

func (m *AddWantListRequest) GetAdd() *WantList {
	if m != nil {
		return m.Add
	}
	return nil
}

type AddWantListResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddWantListResponse) Reset()         { *m = AddWantListResponse{} }
func (m *AddWantListResponse) String() string { return proto.CompactTextString(m) }
func (*AddWantListResponse) ProtoMessage()    {}
func (*AddWantListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c74c703880358ab0, []int{4}
}

func (m *AddWantListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddWantListResponse.Unmarshal(m, b)
}
func (m *AddWantListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddWantListResponse.Marshal(b, m, deterministic)
}
func (m *AddWantListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddWantListResponse.Merge(m, src)
}
func (m *AddWantListResponse) XXX_Size() int {
	return xxx_messageInfo_AddWantListResponse.Size(m)
}
func (m *AddWantListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddWantListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddWantListResponse proto.InternalMessageInfo

type GetWantListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWantListRequest) Reset()         { *m = GetWantListRequest{} }
func (m *GetWantListRequest) String() string { return proto.CompactTextString(m) }
func (*GetWantListRequest) ProtoMessage()    {}
func (*GetWantListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c74c703880358ab0, []int{5}
}

func (m *GetWantListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWantListRequest.Unmarshal(m, b)
}
func (m *GetWantListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWantListRequest.Marshal(b, m, deterministic)
}
func (m *GetWantListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWantListRequest.Merge(m, src)
}
func (m *GetWantListRequest) XXX_Size() int {
	return xxx_messageInfo_GetWantListRequest.Size(m)
}
func (m *GetWantListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWantListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWantListRequest proto.InternalMessageInfo

type GetWantListResponse struct {
	Lists                []*WantList `protobuf:"bytes,1,rep,name=lists,proto3" json:"lists,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetWantListResponse) Reset()         { *m = GetWantListResponse{} }
func (m *GetWantListResponse) String() string { return proto.CompactTextString(m) }
func (*GetWantListResponse) ProtoMessage()    {}
func (*GetWantListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c74c703880358ab0, []int{6}
}

func (m *GetWantListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWantListResponse.Unmarshal(m, b)
}
func (m *GetWantListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWantListResponse.Marshal(b, m, deterministic)
}
func (m *GetWantListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWantListResponse.Merge(m, src)
}
func (m *GetWantListResponse) XXX_Size() int {
	return xxx_messageInfo_GetWantListResponse.Size(m)
}
func (m *GetWantListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWantListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetWantListResponse proto.InternalMessageInfo

func (m *GetWantListResponse) GetLists() []*WantList {
	if m != nil {
		return m.Lists
	}
	return nil
}

func init() {
	proto.RegisterEnum("wantslist.WantListEntry_Status", WantListEntry_Status_name, WantListEntry_Status_value)
	proto.RegisterType((*Config)(nil), "wantslist.Config")
	proto.RegisterType((*WantListEntry)(nil), "wantslist.WantListEntry")
	proto.RegisterType((*WantList)(nil), "wantslist.WantList")
	proto.RegisterType((*AddWantListRequest)(nil), "wantslist.AddWantListRequest")
	proto.RegisterType((*AddWantListResponse)(nil), "wantslist.AddWantListResponse")
	proto.RegisterType((*GetWantListRequest)(nil), "wantslist.GetWantListRequest")
	proto.RegisterType((*GetWantListResponse)(nil), "wantslist.GetWantListResponse")
}

func init() { proto.RegisterFile("wantslist.proto", fileDescriptor_c74c703880358ab0) }

var fileDescriptor_c74c703880358ab0 = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcf, 0x4f, 0xf2, 0x40,
	0x10, 0xa5, 0xf4, 0x6b, 0x03, 0xd3, 0xef, 0xfb, 0xc0, 0x01, 0x93, 0xc6, 0x44, 0x25, 0x9b, 0x98,
	0xa0, 0x87, 0x1e, 0xe0, 0xe0, 0xc1, 0x8b, 0x04, 0x1a, 0x2f, 0x08, 0xa4, 0xc5, 0x70, 0x24, 0x95,
	0xae, 0xa6, 0x09, 0x6c, 0xb1, 0xbb, 0xf8, 0xeb, 0x1f, 0xf2, 0xe4, 0xff, 0x68, 0x76, 0x0b, 0x48,
	0x05, 0x0e, 0xde, 0xa6, 0x6f, 0xde, 0xbc, 0x79, 0x6f, 0xba, 0x50, 0x7a, 0x09, 0x98, 0xe0, 0xd3,
	0x88, 0x0b, 0x67, 0x9e, 0xc4, 0x22, 0xc6, 0xe2, 0x1a, 0x20, 0x4d, 0x30, 0xdb, 0x31, 0x7b, 0x88,
	0x1e, 0xf1, 0x1c, 0x0c, 0x89, 0x70, 0x5b, 0xab, 0xe9, 0x75, 0xab, 0x51, 0x71, 0xbe, 0xa7, 0x46,
	0x01, 0x13, 0xdd, 0x88, 0x0b, 0x2f, 0x65, 0x90, 0x0f, 0x0d, 0xfe, 0xad, 0x30, 0x97, 0x89, 0xe4,
	0x0d, 0x11, 0xfe, 0x48, 0xba, 0xad, 0xd5, 0xb4, 0xba, 0xe1, 0xa9, 0x1a, 0xab, 0x60, 0x44, 0x2c,
	0xa4, 0xaf, 0x76, 0x5e, 0x81, 0xe9, 0x07, 0x5e, 0x82, 0xc9, 0x45, 0x20, 0x16, 0xdc, 0xd6, 0x6b,
	0x5a, 0xfd, 0x7f, 0xe3, 0x74, 0xc7, 0x1e, 0xa5, 0xe9, 0xf8, 0x8a, 0xe6, 0x2d, 0xe9, 0xd2, 0x69,
	0x8a, 0x60, 0x09, 0xac, 0xbb, 0xde, 0xc0, 0xeb, 0xb7, 0x5d, 0xdf, 0x77, 0x3b, 0xe5, 0x1c, 0x02,
	0x98, 0xa3, 0x56, 0x6f, 0xe8, 0x76, 0xca, 0x1a, 0xfe, 0x85, 0x42, 0xbb, 0x7f, 0x3b, 0xe8, 0xba,
	0x43, 0xb7, 0xac, 0x93, 0x77, 0x28, 0xac, 0x44, 0xa5, 0x47, 0x16, 0xcc, 0xa8, 0xf2, 0x58, 0xf4,
	0x54, 0x8d, 0x0e, 0x18, 0x6a, 0xbd, 0x9d, 0x57, 0xa1, 0xed, 0x7d, 0x66, 0xbc, 0x94, 0x86, 0x17,
	0x70, 0x30, 0x0d, 0xb8, 0x18, 0xcf, 0x93, 0x78, 0x42, 0x39, 0x1f, 0x8b, 0x68, 0x46, 0x55, 0x10,
	0xdd, 0x2b, 0xc9, 0xc6, 0x20, 0xc5, 0x87, 0xd1, 0x8c, 0x92, 0x2b, 0xc0, 0x56, 0x18, 0xae, 0x6f,
	0x47, 0x9f, 0x16, 0x94, 0x0b, 0x3c, 0x03, 0x3d, 0x08, 0x43, 0x65, 0x62, 0xcf, 0x91, 0x65, 0x9f,
	0x1c, 0x42, 0x25, 0x33, 0xcc, 0xe7, 0x31, 0xe3, 0x94, 0x54, 0x01, 0x6f, 0xa8, 0xf8, 0xa1, 0x49,
	0xae, 0xa1, 0x92, 0x41, 0x53, 0xf2, 0x2f, 0xfe, 0x68, 0xe3, 0x53, 0x03, 0x4b, 0x62, 0x3e, 0x4d,
	0x9e, 0xa3, 0x09, 0xc5, 0x1e, 0x58, 0x1b, 0xeb, 0xf1, 0x78, 0x63, 0x74, 0x3b, 0xd3, 0xd1, 0xc9,
	0xbe, 0xf6, 0xd2, 0x75, 0x4e, 0xea, 0x6d, 0x38, 0xcc, 0xe8, 0x6d, 0xe7, 0xc9, 0xe8, 0xed, 0x08,
	0x46, 0x72, 0xf7, 0xa6, 0x7a, 0xc8, 0xcd, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x45, 0x9c, 0x46,
	0x29, 0xdb, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WantServiceClient is the client API for WantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WantServiceClient interface {
	AddWantList(ctx context.Context, in *AddWantListRequest, opts ...grpc.CallOption) (*AddWantListResponse, error)
	GetWantList(ctx context.Context, in *GetWantListRequest, opts ...grpc.CallOption) (*GetWantListResponse, error)
}

type wantServiceClient struct {
	cc *grpc.ClientConn
}

func NewWantServiceClient(cc *grpc.ClientConn) WantServiceClient {
	return &wantServiceClient{cc}
}

func (c *wantServiceClient) AddWantList(ctx context.Context, in *AddWantListRequest, opts ...grpc.CallOption) (*AddWantListResponse, error) {
	out := new(AddWantListResponse)
	err := c.cc.Invoke(ctx, "/wantslist.WantService/AddWantList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wantServiceClient) GetWantList(ctx context.Context, in *GetWantListRequest, opts ...grpc.CallOption) (*GetWantListResponse, error) {
	out := new(GetWantListResponse)
	err := c.cc.Invoke(ctx, "/wantslist.WantService/GetWantList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WantServiceServer is the server API for WantService service.
type WantServiceServer interface {
	AddWantList(context.Context, *AddWantListRequest) (*AddWantListResponse, error)
	GetWantList(context.Context, *GetWantListRequest) (*GetWantListResponse, error)
}

func RegisterWantServiceServer(s *grpc.Server, srv WantServiceServer) {
	s.RegisterService(&_WantService_serviceDesc, srv)
}

func _WantService_AddWantList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddWantListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WantServiceServer).AddWantList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wantslist.WantService/AddWantList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WantServiceServer).AddWantList(ctx, req.(*AddWantListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WantService_GetWantList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWantListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WantServiceServer).GetWantList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wantslist.WantService/GetWantList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WantServiceServer).GetWantList(ctx, req.(*GetWantListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WantService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wantslist.WantService",
	HandlerType: (*WantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddWantList",
			Handler:    _WantService_AddWantList_Handler,
		},
		{
			MethodName: "GetWantList",
			Handler:    _WantService_GetWantList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wantslist.proto",
}
