// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// WantServiceClient is the client API for WantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WantServiceClient interface {
	AddWantList(ctx context.Context, in *AddWantListRequest, opts ...grpc.CallOption) (*AddWantListResponse, error)
	GetWantList(ctx context.Context, in *GetWantListRequest, opts ...grpc.CallOption) (*GetWantListResponse, error)
	DeleteWantList(ctx context.Context, in *DeleteWantlistRequest, opts ...grpc.CallOption) (*DeleteWantlistResponse, error)
}

type wantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWantServiceClient(cc grpc.ClientConnInterface) WantServiceClient {
	return &wantServiceClient{cc}
}

func (c *wantServiceClient) AddWantList(ctx context.Context, in *AddWantListRequest, opts ...grpc.CallOption) (*AddWantListResponse, error) {
	out := new(AddWantListResponse)
	err := c.cc.Invoke(ctx, "/wantslist.WantService/AddWantList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wantServiceClient) GetWantList(ctx context.Context, in *GetWantListRequest, opts ...grpc.CallOption) (*GetWantListResponse, error) {
	out := new(GetWantListResponse)
	err := c.cc.Invoke(ctx, "/wantslist.WantService/GetWantList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wantServiceClient) DeleteWantList(ctx context.Context, in *DeleteWantlistRequest, opts ...grpc.CallOption) (*DeleteWantlistResponse, error) {
	out := new(DeleteWantlistResponse)
	err := c.cc.Invoke(ctx, "/wantslist.WantService/DeleteWantList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WantServiceServer is the server API for WantService service.
// All implementations should embed UnimplementedWantServiceServer
// for forward compatibility
type WantServiceServer interface {
	AddWantList(context.Context, *AddWantListRequest) (*AddWantListResponse, error)
	GetWantList(context.Context, *GetWantListRequest) (*GetWantListResponse, error)
	DeleteWantList(context.Context, *DeleteWantlistRequest) (*DeleteWantlistResponse, error)
}

// UnimplementedWantServiceServer should be embedded to have forward compatible implementations.
type UnimplementedWantServiceServer struct {
}

func (UnimplementedWantServiceServer) AddWantList(context.Context, *AddWantListRequest) (*AddWantListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddWantList not implemented")
}
func (UnimplementedWantServiceServer) GetWantList(context.Context, *GetWantListRequest) (*GetWantListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWantList not implemented")
}
func (UnimplementedWantServiceServer) DeleteWantList(context.Context, *DeleteWantlistRequest) (*DeleteWantlistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWantList not implemented")
}

// UnsafeWantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WantServiceServer will
// result in compilation errors.
type UnsafeWantServiceServer interface {
	mustEmbedUnimplementedWantServiceServer()
}

func RegisterWantServiceServer(s grpc.ServiceRegistrar, srv WantServiceServer) {
	s.RegisterService(&_WantService_serviceDesc, srv)
}

func _WantService_AddWantList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddWantListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WantServiceServer).AddWantList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wantslist.WantService/AddWantList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WantServiceServer).AddWantList(ctx, req.(*AddWantListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WantService_GetWantList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWantListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WantServiceServer).GetWantList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wantslist.WantService/GetWantList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WantServiceServer).GetWantList(ctx, req.(*GetWantListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WantService_DeleteWantList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWantlistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WantServiceServer).DeleteWantList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wantslist.WantService/DeleteWantList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WantServiceServer).DeleteWantList(ctx, req.(*DeleteWantlistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WantService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wantslist.WantService",
	HandlerType: (*WantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddWantList",
			Handler:    _WantService_AddWantList_Handler,
		},
		{
			MethodName: "GetWantList",
			Handler:    _WantService_GetWantList_Handler,
		},
		{
			MethodName: "DeleteWantList",
			Handler:    _WantService_DeleteWantList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wantslist.proto",
}
