// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: wantslist.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WantListEntry_Status int32

const (
	WantListEntry_UNPROCESSED WantListEntry_Status = 0
	WantListEntry_WANTED      WantListEntry_Status = 1
	WantListEntry_LIMBO       WantListEntry_Status = 2
	WantListEntry_COMPLETE    WantListEntry_Status = 3
)

// Enum value maps for WantListEntry_Status.
var (
	WantListEntry_Status_name = map[int32]string{
		0: "UNPROCESSED",
		1: "WANTED",
		2: "LIMBO",
		3: "COMPLETE",
	}
	WantListEntry_Status_value = map[string]int32{
		"UNPROCESSED": 0,
		"WANTED":      1,
		"LIMBO":       2,
		"COMPLETE":    3,
	}
)

func (x WantListEntry_Status) Enum() *WantListEntry_Status {
	p := new(WantListEntry_Status)
	*p = x
	return p
}

func (x WantListEntry_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WantListEntry_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_wantslist_proto_enumTypes[0].Descriptor()
}

func (WantListEntry_Status) Type() protoreflect.EnumType {
	return &file_wantslist_proto_enumTypes[0]
}

func (x WantListEntry_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WantListEntry_Status.Descriptor instead.
func (WantListEntry_Status) EnumDescriptor() ([]byte, []int) {
	return file_wantslist_proto_rawDescGZIP(), []int{1, 0}
}

type WantList_WantlistType int32

const (
	WantList_STANDARD WantList_WantlistType = 0
	WantList_RAPID    WantList_WantlistType = 1
	WantList_ALL_IN   WantList_WantlistType = 2
)

// Enum value maps for WantList_WantlistType.
var (
	WantList_WantlistType_name = map[int32]string{
		0: "STANDARD",
		1: "RAPID",
		2: "ALL_IN",
	}
	WantList_WantlistType_value = map[string]int32{
		"STANDARD": 0,
		"RAPID":    1,
		"ALL_IN":   2,
	}
)

func (x WantList_WantlistType) Enum() *WantList_WantlistType {
	p := new(WantList_WantlistType)
	*p = x
	return p
}

func (x WantList_WantlistType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WantList_WantlistType) Descriptor() protoreflect.EnumDescriptor {
	return file_wantslist_proto_enumTypes[1].Descriptor()
}

func (WantList_WantlistType) Type() protoreflect.EnumType {
	return &file_wantslist_proto_enumTypes[1]
}

func (x WantList_WantlistType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WantList_WantlistType.Descriptor instead.
func (WantList_WantlistType) EnumDescriptor() ([]byte, []int) {
	return file_wantslist_proto_rawDescGZIP(), []int{2, 0}
}

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lists      []*WantList `protobuf:"bytes,1,rep,name=lists,proto3" json:"lists,omitempty"`
	LastChange int64       `protobuf:"varint,2,opt,name=last_change,json=lastChange,proto3" json:"last_change,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wantslist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_wantslist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_wantslist_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetLists() []*WantList {
	if x != nil {
		return x.Lists
	}
	return nil
}

func (x *Config) GetLastChange() int64 {
	if x != nil {
		return x.LastChange
	}
	return 0
}

type WantListEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Want   int32                `protobuf:"varint,1,opt,name=want,proto3" json:"want,omitempty"`
	Index  int32                `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Status WantListEntry_Status `protobuf:"varint,3,opt,name=status,proto3,enum=wantslist.WantListEntry_Status" json:"status,omitempty"`
}

func (x *WantListEntry) Reset() {
	*x = WantListEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wantslist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WantListEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WantListEntry) ProtoMessage() {}

func (x *WantListEntry) ProtoReflect() protoreflect.Message {
	mi := &file_wantslist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WantListEntry.ProtoReflect.Descriptor instead.
func (*WantListEntry) Descriptor() ([]byte, []int) {
	return file_wantslist_proto_rawDescGZIP(), []int{1}
}

func (x *WantListEntry) GetWant() int32 {
	if x != nil {
		return x.Want
	}
	return 0
}

func (x *WantListEntry) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *WantListEntry) GetStatus() WantListEntry_Status {
	if x != nil {
		return x.Status
	}
	return WantListEntry_UNPROCESSED
}

type WantList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name            string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Wants           []*WantListEntry      `protobuf:"bytes,2,rep,name=wants,proto3" json:"wants,omitempty"`
	LastProcessTime int64                 `protobuf:"varint,3,opt,name=last_process_time,json=lastProcessTime,proto3" json:"last_process_time,omitempty"`
	Year            int32                 `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	Type            WantList_WantlistType `protobuf:"varint,5,opt,name=type,proto3,enum=wantslist.WantList_WantlistType" json:"type,omitempty"`
	TimeAdded       int64                 `protobuf:"varint,6,opt,name=time_added,json=timeAdded,proto3" json:"time_added,omitempty"`
	RetireTime      int64                 `protobuf:"varint,7,opt,name=retire_time,json=retireTime,proto3" json:"retire_time,omitempty"`
}

func (x *WantList) Reset() {
	*x = WantList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wantslist_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WantList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WantList) ProtoMessage() {}

func (x *WantList) ProtoReflect() protoreflect.Message {
	mi := &file_wantslist_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WantList.ProtoReflect.Descriptor instead.
func (*WantList) Descriptor() ([]byte, []int) {
	return file_wantslist_proto_rawDescGZIP(), []int{2}
}

func (x *WantList) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WantList) GetWants() []*WantListEntry {
	if x != nil {
		return x.Wants
	}
	return nil
}

func (x *WantList) GetLastProcessTime() int64 {
	if x != nil {
		return x.LastProcessTime
	}
	return 0
}

func (x *WantList) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *WantList) GetType() WantList_WantlistType {
	if x != nil {
		return x.Type
	}
	return WantList_STANDARD
}

func (x *WantList) GetTimeAdded() int64 {
	if x != nil {
		return x.TimeAdded
	}
	return 0
}

func (x *WantList) GetRetireTime() int64 {
	if x != nil {
		return x.RetireTime
	}
	return 0
}

type AddWantListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Add *WantList `protobuf:"bytes,1,opt,name=add,proto3" json:"add,omitempty"`
}

func (x *AddWantListRequest) Reset() {
	*x = AddWantListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wantslist_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddWantListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWantListRequest) ProtoMessage() {}

func (x *AddWantListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wantslist_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWantListRequest.ProtoReflect.Descriptor instead.
func (*AddWantListRequest) Descriptor() ([]byte, []int) {
	return file_wantslist_proto_rawDescGZIP(), []int{3}
}

func (x *AddWantListRequest) GetAdd() *WantList {
	if x != nil {
		return x.Add
	}
	return nil
}

type AddWantListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddWantListResponse) Reset() {
	*x = AddWantListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wantslist_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddWantListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWantListResponse) ProtoMessage() {}

func (x *AddWantListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wantslist_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWantListResponse.ProtoReflect.Descriptor instead.
func (*AddWantListResponse) Descriptor() ([]byte, []int) {
	return file_wantslist_proto_rawDescGZIP(), []int{4}
}

type GetWantListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetWantListRequest) Reset() {
	*x = GetWantListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wantslist_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWantListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWantListRequest) ProtoMessage() {}

func (x *GetWantListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wantslist_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWantListRequest.ProtoReflect.Descriptor instead.
func (*GetWantListRequest) Descriptor() ([]byte, []int) {
	return file_wantslist_proto_rawDescGZIP(), []int{5}
}

type GetWantListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lists []*WantList `protobuf:"bytes,1,rep,name=lists,proto3" json:"lists,omitempty"`
}

func (x *GetWantListResponse) Reset() {
	*x = GetWantListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wantslist_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWantListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWantListResponse) ProtoMessage() {}

func (x *GetWantListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wantslist_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWantListResponse.ProtoReflect.Descriptor instead.
func (*GetWantListResponse) Descriptor() ([]byte, []int) {
	return file_wantslist_proto_rawDescGZIP(), []int{6}
}

func (x *GetWantListResponse) GetLists() []*WantList {
	if x != nil {
		return x.Lists
	}
	return nil
}

type DeleteWantlistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DeleteWantlistRequest) Reset() {
	*x = DeleteWantlistRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wantslist_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteWantlistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWantlistRequest) ProtoMessage() {}

func (x *DeleteWantlistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wantslist_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWantlistRequest.ProtoReflect.Descriptor instead.
func (*DeleteWantlistRequest) Descriptor() ([]byte, []int) {
	return file_wantslist_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteWantlistRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteWantlistResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteWantlistResponse) Reset() {
	*x = DeleteWantlistResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wantslist_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteWantlistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWantlistResponse) ProtoMessage() {}

func (x *DeleteWantlistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wantslist_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWantlistResponse.ProtoReflect.Descriptor instead.
func (*DeleteWantlistResponse) Descriptor() ([]byte, []int) {
	return file_wantslist_proto_rawDescGZIP(), []int{8}
}

var File_wantslist_proto protoreflect.FileDescriptor

var file_wantslist_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x77, 0x61, 0x6e, 0x74, 0x73, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x77, 0x61, 0x6e, 0x74, 0x73, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x54, 0x0a, 0x06,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x29, 0x0a, 0x05, 0x6c, 0x69, 0x73, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x77, 0x61, 0x6e, 0x74, 0x73, 0x6c, 0x69, 0x73,
	0x74, 0x2e, 0x57, 0x61, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x05, 0x6c, 0x69, 0x73, 0x74,
	0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x22, 0xb2, 0x01, 0x0a, 0x0d, 0x57, 0x61, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x61, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x77, 0x61, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x37,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f,
	0x2e, 0x77, 0x61, 0x6e, 0x74, 0x73, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x57, 0x61, 0x6e, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x3e, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x53, 0x53, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x57, 0x41, 0x4e, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x09,
	0x0a, 0x05, 0x4c, 0x49, 0x4d, 0x42, 0x4f, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x4f, 0x4d,
	0x50, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x03, 0x22, 0xb9, 0x02, 0x0a, 0x08, 0x57, 0x61, 0x6e, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x05, 0x77, 0x61, 0x6e, 0x74,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x77, 0x61, 0x6e, 0x74, 0x73, 0x6c,
	0x69, 0x73, 0x74, 0x2e, 0x57, 0x61, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x05, 0x77, 0x61, 0x6e, 0x74, 0x73, 0x12, 0x2a, 0x0a, 0x11, 0x6c, 0x61, 0x73, 0x74,
	0x5f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0f, 0x6c, 0x61, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x34, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x77, 0x61, 0x6e, 0x74, 0x73, 0x6c, 0x69,
	0x73, 0x74, 0x2e, 0x57, 0x61, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x2e, 0x57, 0x61, 0x6e, 0x74,
	0x6c, 0x69, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x61, 0x64, 0x64, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x41, 0x64, 0x64, 0x65, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x72, 0x65, 0x74, 0x69, 0x72, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x72, 0x65, 0x74, 0x69, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x33,
	0x0a, 0x0c, 0x57, 0x61, 0x6e, 0x74, 0x6c, 0x69, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c,
	0x0a, 0x08, 0x53, 0x54, 0x41, 0x4e, 0x44, 0x41, 0x52, 0x44, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05,
	0x52, 0x41, 0x50, 0x49, 0x44, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x4c, 0x4c, 0x5f, 0x49,
	0x4e, 0x10, 0x02, 0x22, 0x3b, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x57, 0x61, 0x6e, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x03, 0x61, 0x64, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x77, 0x61, 0x6e, 0x74, 0x73, 0x6c, 0x69,
	0x73, 0x74, 0x2e, 0x57, 0x61, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x03, 0x61, 0x64, 0x64,
	0x22, 0x15, 0x0a, 0x13, 0x41, 0x64, 0x64, 0x57, 0x61, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x57, 0x61,
	0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x40, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x57, 0x61, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x6c, 0x69, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x77, 0x61, 0x6e, 0x74, 0x73, 0x6c, 0x69, 0x73, 0x74, 0x2e,
	0x57, 0x61, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x05, 0x6c, 0x69, 0x73, 0x74, 0x73, 0x22,
	0x2b, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x61, 0x6e, 0x74, 0x6c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x18, 0x0a, 0x16,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x61, 0x6e, 0x74, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x86, 0x02, 0x0a, 0x0b, 0x57, 0x61, 0x6e, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4e, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x57, 0x61, 0x6e,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1d, 0x2e, 0x77, 0x61, 0x6e, 0x74, 0x73, 0x6c, 0x69, 0x73,
	0x74, 0x2e, 0x41, 0x64, 0x64, 0x57, 0x61, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x77, 0x61, 0x6e, 0x74, 0x73, 0x6c, 0x69, 0x73, 0x74,
	0x2e, 0x41, 0x64, 0x64, 0x57, 0x61, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x57, 0x61, 0x6e,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1d, 0x2e, 0x77, 0x61, 0x6e, 0x74, 0x73, 0x6c, 0x69, 0x73,
	0x74, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x61, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x77, 0x61, 0x6e, 0x74, 0x73, 0x6c, 0x69, 0x73, 0x74,
	0x2e, 0x47, 0x65, 0x74, 0x57, 0x61, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x57, 0x61, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x20, 0x2e, 0x77, 0x61, 0x6e, 0x74, 0x73,
	0x6c, 0x69, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x61, 0x6e, 0x74, 0x6c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x77, 0x61, 0x6e,
	0x74, 0x73, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x61, 0x6e,
	0x74, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x72,
	0x6f, 0x74, 0x68, 0x65, 0x72, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2f, 0x77, 0x61, 0x6e, 0x74, 0x73,
	0x6c, 0x69, 0x73, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_wantslist_proto_rawDescOnce sync.Once
	file_wantslist_proto_rawDescData = file_wantslist_proto_rawDesc
)

func file_wantslist_proto_rawDescGZIP() []byte {
	file_wantslist_proto_rawDescOnce.Do(func() {
		file_wantslist_proto_rawDescData = protoimpl.X.CompressGZIP(file_wantslist_proto_rawDescData)
	})
	return file_wantslist_proto_rawDescData
}

var file_wantslist_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_wantslist_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_wantslist_proto_goTypes = []interface{}{
	(WantListEntry_Status)(0),      // 0: wantslist.WantListEntry.Status
	(WantList_WantlistType)(0),     // 1: wantslist.WantList.WantlistType
	(*Config)(nil),                 // 2: wantslist.Config
	(*WantListEntry)(nil),          // 3: wantslist.WantListEntry
	(*WantList)(nil),               // 4: wantslist.WantList
	(*AddWantListRequest)(nil),     // 5: wantslist.AddWantListRequest
	(*AddWantListResponse)(nil),    // 6: wantslist.AddWantListResponse
	(*GetWantListRequest)(nil),     // 7: wantslist.GetWantListRequest
	(*GetWantListResponse)(nil),    // 8: wantslist.GetWantListResponse
	(*DeleteWantlistRequest)(nil),  // 9: wantslist.DeleteWantlistRequest
	(*DeleteWantlistResponse)(nil), // 10: wantslist.DeleteWantlistResponse
}
var file_wantslist_proto_depIdxs = []int32{
	4,  // 0: wantslist.Config.lists:type_name -> wantslist.WantList
	0,  // 1: wantslist.WantListEntry.status:type_name -> wantslist.WantListEntry.Status
	3,  // 2: wantslist.WantList.wants:type_name -> wantslist.WantListEntry
	1,  // 3: wantslist.WantList.type:type_name -> wantslist.WantList.WantlistType
	4,  // 4: wantslist.AddWantListRequest.add:type_name -> wantslist.WantList
	4,  // 5: wantslist.GetWantListResponse.lists:type_name -> wantslist.WantList
	5,  // 6: wantslist.WantService.AddWantList:input_type -> wantslist.AddWantListRequest
	7,  // 7: wantslist.WantService.GetWantList:input_type -> wantslist.GetWantListRequest
	9,  // 8: wantslist.WantService.DeleteWantList:input_type -> wantslist.DeleteWantlistRequest
	6,  // 9: wantslist.WantService.AddWantList:output_type -> wantslist.AddWantListResponse
	8,  // 10: wantslist.WantService.GetWantList:output_type -> wantslist.GetWantListResponse
	10, // 11: wantslist.WantService.DeleteWantList:output_type -> wantslist.DeleteWantlistResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_wantslist_proto_init() }
func file_wantslist_proto_init() {
	if File_wantslist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wantslist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wantslist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WantListEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wantslist_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WantList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wantslist_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddWantListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wantslist_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddWantListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wantslist_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWantListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wantslist_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWantListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wantslist_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteWantlistRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wantslist_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteWantlistResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wantslist_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wantslist_proto_goTypes,
		DependencyIndexes: file_wantslist_proto_depIdxs,
		EnumInfos:         file_wantslist_proto_enumTypes,
		MessageInfos:      file_wantslist_proto_msgTypes,
	}.Build()
	File_wantslist_proto = out.File
	file_wantslist_proto_rawDesc = nil
	file_wantslist_proto_goTypes = nil
	file_wantslist_proto_depIdxs = nil
}
